---
- hosts: all
  become: yes
  tasks:
  - name: install git,tree,wget into nodes
    apt:
     name: git
    state: present
  - name: install tree
    apt:
     name: tree
     state: present
  - name: install wget
    apt:
     name: wget 
    state: present 